apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-runner-docker-cache
  namespace: forgejo-runner
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi