apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  targetNamespace: longhorn-system
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: "1.11.0"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 12h
